### PR TITLE
Add WP-CLI commands

### PR DESCRIPTION
**Pull request by tfrommen**
This PR adds two WP-CLI commands that can be useful when debugging.

Changes:
- Add `wp simple-saml` WP-CLI command.
- Add `wp simple-saml response` WP-CLI command.
- Abstract portion of `action_metadata` into `get_metadata` to be able to use for WP-CLI.
- Abstract portion of `get_sso_user` into `process_response` to be able to use for WP-CLI.
- Usage of both `action_metadata` and `get_sso_user` should remain unchanged.

## `wp simple-saml`

```shell
NAME

  wp simple-saml

DESCRIPTION

  Inspect SAML settings.

SYNOPSIS

  wp simple-saml <command>

SUBCOMMANDS

  attribute-mapping      Print mapping of SAML attributes to user data attributes.
  metadata               Print SP metadata (XML).
  response               Inspect SAML response data.

EXAMPLES

    # Print attribute mapping.
    $ wp simple-saml attribute-mapping
    +------------+------------+
    | Field      | Value      |
    +------------+------------+
    | user_login | EmployeeID |
    | user_email | EmailID    |
    | first_name | FirstName  |
    | last_name  | LastName   |
    +------------+------------+

    # Print SP metadata (XML).
    $ wp simple-saml metadata
    <?xml version="1.0"?>
    <md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"
                         validUntil="2022-11-11T11:11:22Z"
                         cacheDuration="PT604800S"
                         entityID="php-saml">
    ...
```

## `wp simple-saml response`

To be able to inspect response data, you would store the SAML response you received in a file.
You can pass any file name as `--file` to the command.
If you don't provide a `--file`, the command defaults to `saml.txt`.

```shell
NAME

  wp simple-saml response

DESCRIPTION

  Inspect SAML response data.

SYNOPSIS

  wp simple-saml response <command>

SUBCOMMANDS

  attribute         Process SAML response and return requested attribute.
  attributes        Process SAML response and return all attributes.
  decode            Decode and print SAML response.
  name-id-data      Process SAML response and return NameID data.
  process           Process SAML response and optionally print SAML2 Auth object.

EXAMPLES

    # Get one SAML attribute.
    $ wp simple-saml response attribute mail
    john@example.com

    # Get all SAML attributes.
    $ wp simple-saml response attributes
    +------------+------------------+
    | Field      | Value            |
    +------------+------------------+
    | user_login | 4815162342       |
    | user_email | john@example.com |
    | first_name | John             |
    | last_name  | Doe              |
    +------------+------------------+

    # Decode SAML response.
    $ wp simple-saml response decode
    <?xml version="1.0"?>
    <samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    ID="_8e8dc5f69a98cc4c1ff3427e5ce34606fd672f91e6" Version="2.0" IssueInstant="2022-11-11T11:11:22Z" Destination="https://example.com/sso/verify"
    InResponseTo="ONELOGIN_4fee3b046395c4e751011e97f8900b5273d56685">
      <saml:Issuer>https://idp.example.com/metadata.php</saml:Issuer>
      <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
    ...

    # Get NameID data.
    $ wp simple-saml response name-id-data
    +-----------------------+-----------------------------------------------------+
    | Field                 | Value                                               |
    +-----------------------+-----------------------------------------------------+
    | NameId                | _ce3d2948b4cf20146dee0a0b3dd6f69b6cf86f62d7         |
    | NameIdFormat          | urn:oasis:names:tc:SAML:2.0:nameid-format:transient |
    | NameIdNameQualifier   |                                                     |
    | NameIdSPNameQualifier | php-saml                                            |
    +-----------------------+-----------------------------------------------------+

    # Process SAML response.
    $ wp simple-saml response process
    Success: SAML response processed.
    Print SAML2 Auth object? [y/n]
```

This also addresses #66.

### CODE REVIEW

**Review by shadyvb — COMMENTED** [review]
LGTM, probably just missing how to log the response or how to get the log from, otherwise the decoding command isn't super useful.

Bonus would be if we have a way to activate/deactivate logging via the cli, unless we have that available somewhere else already ( can't remember ottomh ).

( also, the linter has some complaints )

**Comment by tfrommen** [comment]
> LGTM, probably just missing how to log the response or how to get the log from, otherwise the decoding command isn't super useful.

Not sure what you mean by this.

The idea for the `wp simple-saml response` commands was to store the recevied `POST` response from the SSO side of things in a file so you can debug something multiple times, and locally or wherever you need.

The `decode` subcommand is to base64-decode the response into a "readable" XML output. Whatever you want to do with this. (Most of the time, you wouldn't need/use it anyway, but instead query specific things you are looking to understand.)


> Bonus would be if we have a way to activate/deactivate logging via the cli, unless we have that available somewhere else already ( can't remember ottomh ).

Also not sure what you mean by this. Do you want to somehow "log" the response data you receive? If yes, depending on your infrastructure setup, you maybe already do. On Altis, for example, you can look at X-Ray logs and see the `SAMLResponse` POST data.


> the linter has some complaints

It does. But not just about the code I added. 😉
Fixing this (or the coding standards) goes way beyond what I was trying to do with this PR, which is provide repeatable (local) debugging capabilities for anyone.

**Comment by shadyvb** [comment]
@tfrommen Yes I meant logging the response that we can decode using the new command. Using XRay logs is a nice way to do, didn't think about it, wasn't even sure they got logged! So maybe we can add a note somewhere in Altis docs for people to surface this tip cc @kovshenin 

Will leave this with @kovshenin to merge / update docs.

**Comment by tfrommen** [comment]
Not sure why this is with you, @kovshenin, but did you have some time to take a look? Having this available would have come in handy yet another time just now. (I can sort of do it locally, but it's unnecessary hassle.)
Thanks!

**Comment by roborourke** [comment]
Think Konstantin is mentioned as Altis Lead but it's not dependent on him. 

@tfrommen there are HM Linter errors though a bunch not on code from this PR so those could be looked at in a follow up. The changes look good to me, I think it warrants a new minor release version.

**Review by roborourke — APPROVED** [review]

**Comment by tfrommen** [comment]
@roborourke thanks for the review.

I followed up on most of the linter issues (all around docs). When I wrote the classes I followed existing structures, including commenting. I have changed that now and improved the classes.
The only things still being flagged are two camelCase property names on `DOMDocument`. For those things, I personally would not add inline annotations, but instead add this to the PHP_CodeSniffer standard. However, this repo doesn't even have one, which is why HM Linter will use the `HM` one.

While at it, I also fixed references to an incorrect default file name, and one place wher `sprintf` was missing.

Would you mind checking again? Thanks!

**Comment by joehoyle** [comment]
@tfrommen sorry for the lack of follow-up here! I don't feel personally capable of reviewing this as I'm not that familiar. @roborourke do you think you can find time to checking? Thank you!

**Review by roborourke — APPROVED** [review]
Sorry @tfrommen, all good now IMO

**Pull request merged**
